server:
  port: 8080
  servlet:
    context-path: /benefits
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/benefits
    username: benefits
    password: ben0147
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
    hibernate:
      ddl-auto: validate
      format_sql: true
      generate_statistics: true
      cache:
        use_second_level_cache: true
        use_query_cache: true
        provider_class: org.hibernate.cache.EhCacheProvider
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  liquibase:
    enabled: true
    default-schema: public
  main:
    banner-mode: off
