server:
  port: 8080
  servlet:
    context-path: /benefits
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/benefits
    username: benefits
    password: ben0147
  jpa:
    open-in-view: false
#    show-sql: true
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        javax:
          cache:
            missing_cache_strategy: create
        format_sql: true
#        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
#  logging:
#    level:
#      org:
#        hibernate:
#          type: trace
  liquibase:
    enabled: true
    default-schema: public
    changeLog: classpath:db/changelog/db.changelog-master.yaml
  main:
    banner-mode: off
    allow-circular-references: true
  application:
    name: A-Benefits

keycloak:
  auth-server-url: http://localhost:8484/auth/
  realm: benefits
  resource: benefits-auth
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: false

springdoc:
  swagger-ui:
    oauth:
      clientId: benefits-auth
      clientSecret: qyYUkad3HmruCk2ZRw3FP9H52lWc9Poq
  oAuthFlow:
    authorizationUrl: http://localhost:8484/auth/realms/benefits/protocol/openid-connect/auth
    tokenUrl: http://localhost:8484/auth/realms/benefits/protocol/openid-connect/token
    use-pkce-with-authorization-code-grant: true
