server:
  port: 8080
  servlet:
    context-path: /benefits

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/benefits
    username: benefits
    password: ben0147
  jpa:
    open-in-view: false
  liquibase:
    enabled: true
    default-schema: public