INSERT INTO locations(country, city) VALUES
('Russia', 'Moscow'),
('Russia', 'St. Petersburg'),
('Russia', 'Kazan'),
('Russia', 'Ekaterinburg'),
('Russia', 'Sochi'),
('Russia', 'Volgograd'),
('Russia', 'Samara'),
('Ukraine', 'Kyiv'),
('Ukraine', 'Odessa'),
('Ukraine', 'Lviv'),
('Ukraine', 'Vinnitsa'),
('Ukraine', 'Zaporozhye'),
('Belarus', 'Minsk'),
('Belarus', 'Vitebsk'),
('Belarus', 'Gomel'),
('Belarus', 'Mogilev'),
('Belarus', 'Brest');
