version: "3.9"

services:
  postgres:
    container_name: postgres_container_keycloak
    image: postgres
    environment:
      POSTGRES_USER: benefits
      POSTGRES_PASSWORD: ben0147
      POSTGRES_DB: benefits
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - keycloak
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container_keycloak
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: benefits@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: ben0147
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - keycloak
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: keycloak_container
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_container_keycloak
      DB_DATABASE: benefits
      DB_USER: benefits
      DB_SCHEMA: public
      DB_PASSWORD: ben0147
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    networks:
      - keycloak
    restart: unless-stopped

networks:
  keycloak:
    driver: bridge

volumes:
  postgres:
  pgadmin: